services:
  nginx:
    extends:
      file: common-services.yml
      service: nginx
    volumes:
      - ./masterportal-code/dist:/var/www/html
      - ./nginx/prod/default.conf:/etc/nginx/templates/default.conf.template
    ports:
      - 80:80
    healthcheck:
      test: curl --fail http://localhost:80/ || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  print:
    extends:
      file: common-services.yml
      service: print
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
