services:
  nginx:
    volumes:
      - ./nginx/ssl/private/localhost.crt:/etc/nginx/ssl/private/localhost.crt
      - ./nginx/ssl/private/localhost.key:/etc/nginx/ssl/private/localhost.key
      - ./nginx/dev/default.conf:/etc/nginx/templates/default.conf.template
    depends_on:
      - masterportal-client
    ports:
      - 443:443
  masterportal-client:
    build:
      context: ./masterportal-client
      args:
        USER_UID: ${UID}
        USER_GID: ${GID}
        USER_NAME: ${UNAME}
        MASTERPORTAL_VERSION: ${MASTERPORTAL_VERSION}
    volumes:
      - ./masterportal:/home/${UNAME}/masterportal
